# Generated by Django 3.1 on 2020-09-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200912_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_on']},
        ),
    ]
