# Generated by Django 3.1 on 2020-11-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20201108_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('-created_at',)},
        ),
    ]
